Country.create(name: 'United Kingdom')
Country.create(name: 'Republic of Ireland')
Country.create(name: 'United States of America')
Country.create(name: 'United Arab Emirates')
Country.create(name: 'France')
Country.create(name: 'Monaco')
Country.create(name: 'Netherlands')
Country.create(name: 'Morocco')
Country.create(name: 'India')
Country.create(name: 'Singapore')
Country.create(name: 'South Africa')
Country.create(name: 'Australia')
Country.create(name: 'Canada')
Country.create(name: 'Sweden')
Country.create(name: 'Chile')
Country.create(name: 'Belgium')

Chapter.create(city: 'London', country_id: Country.find_by(name: 'United Kingdom').id, lead: 'Tim Heard', email: 'tim@circleofyi.com')
Chapter.create(city: 'Los Angeles', country_id: Country.find_by(name: 'United States of America').id, lead: 'Justin Deshaw', email: 'justin.deshaw@gmail.com')
Chapter.create(city: 'Washington DC', country_id: Country.find_by(name: 'United States of America').id, lead: 'John Balkam', email: 'jrbalkam@gmail.com')
Chapter.create(city: 'Boston', country_id: Country.find_by(name: 'United States of America').id, lead: 'Alejandra Grupp', email: 'alejandragrupp@gmail.com')
Chapter.create(city: 'New York City', country_id: Country.find_by(name: 'United States of America').id, lead: 'Hallie Stebbins', email: 'hallie.stebbins@gmail.com')
Chapter.create(city: 'Pittsburgh', country_id: Country.find_by(name: 'United States of America').id, lead: 'Meg Trite', email: 'megtrite@gmail.com')
Chapter.create(city: 'Chicago', country_id: Country.find_by(name: 'United States of America').id, lead: 'Jack Redding', email: 'megtrite@gmail.com')
Chapter.create(city: 'Dublin', country_id: Country.find_by(name: 'United States of America').id, lead: 'Ciara Keane', email: '')
Chapter.create(city: 'Birmingham', country_id: Country.find_by(name: 'United Kingdom').id, lead: 'Sally Eaves', email: 'business@sallyeaves.co.uk')
Chapter.create(city: 'Paris', country_id: Country.find_by(name: 'France').id, lead: 'Anna Donna-Hie', email: 'annadonahie@gmail.com')
Chapter.create(city: 'Monaco', country_id: Country.find_by(name: 'France').id, lead: 'Dara Miller', email: 'miller.dara@gmail.com')
Chapter.create(city: 'Amsterdam', country_id: Country.find_by(name: 'Netherlands').id, lead: 'Aouatif Tawfik', email: 'aouatif.tawfik@unilever.com')
Chapter.create(city: 'Casablanca', country_id: Country.find_by(name: 'Morocco').id, lead: 'Guillaume Vigier', email: 'gvigier.mazars@gmail.com')
Chapter.create(city: 'New Delhi', country_id: Country.find_by(name: 'India').id, lead: 'Ashutosh Kumar', email: 'helloashu.kumar@gmail.com')
Chapter.create(city: 'Singapore', country_id: Country.find_by(name: 'Singapore').id, lead: 'David Nosibor', email: 'david.nosibor@mazars.com.sg')
Chapter.create(city: 'Johannesburg', country_id: Country.find_by(name: 'South Africa').id, lead: 'Fabio Henriquez', email: '')
Chapter.create(city: 'Sydney', country_id: Country.find_by(name: 'Australia').id, lead: 'Laurie Brown', email: 'laurie.s.brown@hotmail.com')
Chapter.create(city: 'Dubai', country_id: Country.find_by(name: 'United Arab Emirates').id, lead: 'Mohamed Abdeljalil', email: '')
Chapter.create(city: 'Toronto', country_id: Country.find_by(name: 'Canada').id, lead: 'Nader Saif', email: '')
Chapter.create(city: 'Stockholm', country_id: Country.find_by(name: 'Sweden').id, lead: 'Jacob Larsson', email: '')
Chapter.create(city: 'Santiago', country_id: Country.find_by(name: 'Chile').id, lead: 'Cristian Guerrero', email: '')
Chapter.create(city: 'Brussels', country_id: Country.find_by(name: 'Belgium').id, lead: 'Jason Stamm', email: '')

# EXISTING USERS
User.create(first_name:'Jack', last_name: 'McGregor', chapter_id:1, email:'jmcgregor@spartaglobal.com', password:'Password1!')
User.create(first_name:'Steely', last_name: 'Dan', chapter_id:1, email:'jmcgregor@spartaglobal.com', password:'Password1!')
